name: Taller CI/CD
run-name: Estamos ejecutando acciones autom√°ticas

on: [push]

jobs:
    MiPrimeraAutomatizacion:
        runs-on: ubuntu-latest
        steps:
            - name: Cargar los fichero de mi repo
              uses: actions/checkout@v6
            - name: Venis ek cibtebudi de ka caroeta
              run: ls -luah .
            